export type Section = {
  n: number
  bookPage: number
  titleDe: string
}

export const SECTIONS: Section[] = [
  { n: 1, bookPage: 2, titleDe: "Die Notwendigkeit einer ausdrücklichen Wiederholung der Frage nach dem Sein" },
  { n: 2, bookPage: 5, titleDe: "Die formale Struktur der Frage nach dem Sein" },
  { n: 3, bookPage: 8, titleDe: "Der ontologische Vorrang der Seinsfrage" },
  { n: 4, bookPage: 11, titleDe: "Der ontische Vorrang der Seinsfrage" },
  { n: 5, bookPage: 15, titleDe: "Die ontologische Analytik des Daseins als Freilegung des Horizontes für eine Interpretation des Sinnes von Sein überhaupt" },
  { n: 6, bookPage: 19, titleDe: "Die Aufgabe einer Destruktion der Geschichte der Ontologie" },
  { n: 7, bookPage: 27, titleDe: "Die phänomenologische Methode der Untersuchung" },
  { n: 8, bookPage: 39, titleDe: "Der Aufriß der Abhandlung" },
  { n: 9, bookPage: 41, titleDe: "Das Thema der Analytik des Daseins" },
  { n: 10, bookPage: 45, titleDe: "Die Abgrenzung der Daseinsanalytik gegen Anthropologie, Psychologie und Biologie" },
  { n: 11, bookPage: 50, titleDe: "Die existenziale Analytik und die Interpretation des primitiven Daseins" },
  { n: 12, bookPage: 52, titleDe: "Die Verzeichnung des In-der-Welt-seins aus der Orientierung am In-Sein als solchem" },
  { n: 13, bookPage: 59, titleDe: "Die Exemplifizierung des In-Seins an einem fundierten Modus. Das Welterkennen" },
  { n: 14, bookPage: 63, titleDe: "Die Idee der Weltlichkeit der Welt überhaupt" },
  { n: 15, bookPage: 66, titleDe: "Das Sein des in der Umwelt begegnenden Seienden" },
  { n: 16, bookPage: 72, titleDe: "Die am innerweltlich Seienden sich meldende Weltmäßigkeit der Umwelt" },
  { n: 17, bookPage: 76, titleDe: "Verweisung und Zeichen" },
  { n: 18, bookPage: 83, titleDe: "Bewandtnis und Bedeutsamkeit; die Weltlichkeit der Welt" },
  { n: 19, bookPage: 89, titleDe: "Die Bestimmung der »Welt« als res extensa" },
  { n: 20, bookPage: 92, titleDe: "Die Fundamente der ontologischen Bestimmung der »Welt«" },
  { n: 21, bookPage: 95, titleDe: "Die hermeneutische Diskussion der cartesischen Ontologie der »Welt«" },
  { n: 22, bookPage: 102, titleDe: "Die Räumlichkeit des innerweltlich Zuhandenen" },
  { n: 23, bookPage: 104, titleDe: "Die Räumlichkeit des In-der-Welt-seins" },
  { n: 24, bookPage: 110, titleDe: "Die Räumlichkeit des Daseins und der Raum" },
  { n: 25, bookPage: 114, titleDe: "Der Ansatz der existenzialen Frage nach dem Wer des Daseins" },
  { n: 26, bookPage: 117, titleDe: "Das Mitdasein der Anderen und das alltägliche Mitsein" },
  { n: 27, bookPage: 126, titleDe: "Das alltägliche Selbstsein und das Man" },
  { n: 28, bookPage: 130, titleDe: "Die Aufgabe einer thematischen Analyse des In-Seins" },
  { n: 29, bookPage: 134, titleDe: "Das Da-sein als Befindlichkeit" },
  { n: 30, bookPage: 140, titleDe: "Die Furcht als ein Modus der Befindlichkeit" },
  { n: 31, bookPage: 142, titleDe: "Das Da-sein als Verstehen" },
  { n: 32, bookPage: 148, titleDe: "Verstehen und Auslegung" },
  { n: 33, bookPage: 154, titleDe: "Die Aussage als abkünftiger Modus der Auslegung" },
  { n: 34, bookPage: 160, titleDe: "Da-sein und Rede. Die Sprache" },
  { n: 35, bookPage: 167, titleDe: "Das Gerede" },
  { n: 36, bookPage: 170, titleDe: "Die Neugier" },
  { n: 37, bookPage: 173, titleDe: "Die Zweideutigkeit" },
  { n: 38, bookPage: 175, titleDe: "Das Verfallen und die Geworfenheit" },
  { n: 39, bookPage: 180, titleDe: "Die Frage nach der ursprünglichen Ganzheit des Strukturganzen des Daseins" },
  { n: 40, bookPage: 184, titleDe: "Die Grundbefindlichkeit der Angst als eine ausgezeichnete Erschlossenheit des Daseins" },
  { n: 41, bookPage: 191, titleDe: "Das Sein des Daseins als Sorge" },
  { n: 42, bookPage: 196, titleDe: "Die Bewährung der existenzialen Interpretation des Daseins als Sorge aus der vorontologischen Selbstauslegung des Daseins" },
  { n: 43, bookPage: 200, titleDe: "Dasein, Weltlichkeit und Realität" },
  { n: 44, bookPage: 212, titleDe: "Dasein, Erschlossenheit und Wahrheit" },
  { n: 45, bookPage: 231, titleDe: "Das Ergebnis der vorbereitenden Fundamentalanalyse des Daseins und die Aufgabe einer ursprünglichen existenzialen Interpretation dieses Seienden" },
  { n: 46, bookPage: 235, titleDe: "Die scheinbare Unmöglichkeit einer ontologischen Erfassung und Bestimmung des daseinsmäßigen Ganzseins" },
  { n: 47, bookPage: 237, titleDe: "Die Erfahrbarkeit des Todes der Anderen und die Erfassungsmöglichkeit eines ganzen Daseins" },
  { n: 48, bookPage: 241, titleDe: "Ausstand, Ende und Ganzheit" },
  { n: 49, bookPage: 246, titleDe: "Die Abgrenzung der existenzialen Analyse des Todes gegenüber möglichen anderen Interpretationen des Phänomens" },
  { n: 50, bookPage: 249, titleDe: "Die Vorzeichnung der existenzialontologischen Struktur des Todes" },
  { n: 51, bookPage: 252, titleDe: "Das Sein zum Tode und die Alltäglichkeit des Daseins" },
  { n: 52, bookPage: 255, titleDe: "Das alltägliche Sein zum Ende und der volle existenziale Begriff des Todes" },
  { n: 53, bookPage: 260, titleDe: "Existenzialer Entwurf eines eigentlichen Seins zum Tode" },
  { n: 54, bookPage: 267, titleDe: "Das Problem der Bezeugung einer eigentlichen existenziellen Möglichkeit" },
  { n: 55, bookPage: 270, titleDe: "Die existenzial-ontologischen Fundamente des Gewissens" },
  { n: 56, bookPage: 272, titleDe: "Der Rufcharakter des Gewissens" },
  { n: 57, bookPage: 274, titleDe: "Das Gewissen als Ruf der Sorge" },
  { n: 58, bookPage: 280, titleDe: "Anrufverstehen und Schuld" },
  { n: 59, bookPage: 289, titleDe: "Die existenziale Interpretation des Gewissens und die vulgäre Gewissensauslegung" },
  { n: 60, bookPage: 295, titleDe: "Die existenziale Struktur des im Gewissen bezeugten eigentlichen Seinkönnens" },
  { n: 61, bookPage: 301, titleDe: "Vorzeichnung des methodischen Schrittes von der Umgrenzung des eigentlichen daseinsmäßigen Ganzseins zur phänomenalen Freilegung der Zeitlichkeit" },
  { n: 62, bookPage: 305, titleDe: "Das existenziell eigentliche Ganzseinkönnen des Daseins als vorlaufende Entschlossenheit" },
  { n: 63, bookPage: 310, titleDe: "Die für eine Interpretation des Seins-sinnes der Sorge gewonnene hermeneutische Situation und der methodische Charakter der existenzialen Analytik überhaupt" },
  { n: 64, bookPage: 316, titleDe: "Sorge und Selbstheit" },
  { n: 65, bookPage: 323, titleDe: "Die Zeitlichkeit als der ontologische Sinn der Sorge" },
  { n: 66, bookPage: 331, titleDe: "Die Zeitlichkeit des Daseins und die aus ihr entspringenden Aufgaben einer ursprünglicheren Wiederholung der existenzialen Analyse" },
  { n: 67, bookPage: 334, titleDe: "Der Grundbestand der existenzialen Verfassung des Daseins und die Vorzeichnung ihrer zeitlichen Interpretation" },
  { n: 68, bookPage: 335, titleDe: "Die Zeitlichkeit der Erschlossenheit überhaupt" },
  { n: 69, bookPage: 350, titleDe: "Die Zeitlichkeit des In-der-Welt-seins und das Problem der Transzendenz der Welt" },
  { n: 70, bookPage: 367, titleDe: "Die Zeitlichkeit der daseinsmäßigen Räumlichkeit" },
  { n: 71, bookPage: 370, titleDe: "Der zeitliche Sinn der Alltäglichkeit des Daseins" },
  { n: 72, bookPage: 372, titleDe: "Die existenzial-ontologische Exposition des Problems der Geschichte" },
  { n: 73, bookPage: 378, titleDe: "Das vulgäre Verständnis der Geschichte und das Geschehen des Daseins" },
  { n: 74, bookPage: 382, titleDe: "Die Grundverfassung der Geschichtlichkeit" },
  { n: 75, bookPage: 387, titleDe: "Die Geschichtlichkeit des Daseins und die Welt-Geschichte" },
  { n: 76, bookPage: 392, titleDe: "Der existenziale Ursprung der Historie aus der Geschichtlichkeit des Daseins" },
  { n: 77, bookPage: 397, titleDe: "Der Zusammenhang der vorstehenden Exposition des Problems der Geschichtlichkeit mit den Forschungen W. Diltheys und den Ideen des Grafen Yorck" },
  { n: 78, bookPage: 404, titleDe: "Die Unvollständigkeit der vorstehenden zeitlichen Analyse des Daseins" },
  { n: 79, bookPage: 406, titleDe: "Die Zeitlichkeit des Daseins und das Besorgen von Zeit" },
  { n: 80, bookPage: 411, titleDe: "Die besorgte Zeit und die Innerzeitigkeit" },
  { n: 81, bookPage: 420, titleDe: "Die Innerzeitigkeit und die Genesis des vulgären Zeitbegriffes" },
  { n: 82, bookPage: 428, titleDe: "Die Abhebung des existenzial-ontologischen Zusammenhangs von Zeitlichkeit, Dasein und Weltzeit gegen Hegels Auffassung der Beziehung zwischen Zeit und Geist" },
  { n: 83, bookPage: 436, titleDe: "Die existenzial-zeitliche Analytik des Daseins und die fundamentalontologische Frage nach dem Sinn von Sein überhaupt" },
]
